room_size: small
probs:
  commonsense: 0.7
  new_location: 0.1
  new_object: 0.1
  switch_person: 0.5
limits:
  heads: null
  tails: null
  names: null
  allow_spaces: True
max_step: 1000
disjoint_entities: True
num_agents: 1
